#!/bin/bash

"$@" &

START=$(date +%s)

printcmd=$(printf "   \033[0;37mDownloading LEGO train files from: %s/%s_child_%s/%s/%s/%s.root\033[0m" $3 $8 $4 $9 "$5" $6)
printf "$printcmd\n" > /dev/tty

printf "   Running downloader: " > /dev/tty
while kill -0 $!; do
  printf "." > /dev/tty
  sleep 2

  if [ "$(( $(date +%s) - $START ))" -gt "10" ]; then
    printf "\r                               " > /dev/tty
    printf "\r   Running downloader: " > /dev/tty
    START=$(date +%s)
  fi

done

printf "\r                      " > /dev/tty
printf "\r   Downloader finished\n\n" > /dev/tty
